### ISSUE TITLE
YoHours: No colon after special day selector

### ISSUE THREAD

**Issue by M1dgard** [PanierAvide/panieravide.github.io#1]
All documentation I found agrees not to have a colon after week selectors, month selectors or monthday selectors.

E.g.:
`week 01-05 Mo,Tu 08:00-10:00; week 06-10 Mo,Tu 10:00-12:00` instead of
~~`week 01-05: Mo,Tu 08:00-10:00; week 06-10: Mo,Tu 10:00-12:00`~~

Personally I abide by the [proposed time domains specification](https://wiki.openstreetmap.org/wiki/Proposed_features/Time_domains), because it is explained much clearer than on Key:opening_hours and Key:opening_hours/specification and seems to boil down to the same.

**Comment by PanierAvide** [comment]
I based my work on [opening_hours specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:separator_for_readability) and this page says that the colon is optional, but was added for readability. YoHours is able to parse opening_hours without this separator. Do you think this can create problems to other piece of software that doesn't take care of that separator ?

**Comment by M1dgard** [comment]
I have never understood the specification, it may be OK to use it to make an implementation for a parser or a generator, but it is way too complicated for mappers.
I don't know if it would cause problems one way or the other, but this is the first time I even see the colon being used.

IMHO having such "optional separators" is a really bad idea. It just adds to the confusion. (So it's the specification's fault.)

**Comment by M1dgard** [comment]
Nice work BTW :)

**Comment by PanierAvide** [comment]
Thanks :) Let's see what the community says about it, of course if it is not used at all, I will remove it.

**Comment by ypid** [comment]
Hi

https://wiki.openstreetmap.org/wiki/Proposed_features/Time_domains is just an proposal. It is nice and compact and also partly outdated and not approved.

The optional colon ([`<separator_for_readability>`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:separator_for_readability) is a tread of. It was made optional by me because I forked opening_hours.js from AMDmi3 and added support for all opening_hours features to it. AMDmi3 did not accept an colon. The other implementation from Netzwolf did not accept opening_hours values without colon …

https://github.com/AMDmi3/opening_hours.js/issues/19

**Comment by M1dgard** [comment]
OK for implementations to support both, but the tagging should be made uniform IMO. The syntax description on [Key:opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours) is such a mess ...

**Comment by ypid** [comment]
What is a mess :unamused: :wink: ?

**Comment by M1dgard** [comment]
The specification is OK for developers, not for mappers. I'm totally fine with that.

The description on [Key:opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours) is good for neither.

That's why I'm drafting a new Key:opening_hours page in my userspace.

**Comment by PanierAvide** [comment]
+1 This is a good idea

**Comment by PanierAvide** [comment]
The optional separator was removed ;)
