### ISSUE TITLE
24/24 is unclickable 

### ISSUE THREAD

**Issue by d1g** [PanierAvide/panieravide.github.io#12]
Not sure if it was oversight or on purpose: http://github.pavie.info/yohours/?oh=24/7

My understanding that they are implemented independently (table header and rest of the table). In fact, there 2 editors at screen and they are not in sync with each other. This is not obvious and may be confusing for users.

PS. columns "Monday", "Sunday" are not checked when "24/7" loaded from URL.

**Comment by PanierAvide** [comment]
The "whole day" header and the rest of the table are synced, and since you can't add two time intervals on the same hours, if the "whole day" header is filled, the rest of the table for this day isn't clickable. This is how works the FullCalendar library, if it's very confusing I can see how to work around this.
From my web browser, calendar is correctly shown when loading 24/7 from URL, what browser are you using ?

**Comment by d1g** [comment]
Okay, they are synced, but there bug when they are not.  Chrome 48.0.2550.0

I pasted url in my browser and hit enter and headers are empty: http://i.snag.gy/OZU5E.jpg. It behaves differently if you click all 7 headers vs fetching from the url.

**Comment by PanierAvide** [comment]
I will check as soon as possible for Chrome. I understand for the different behaviour, I will fix it ;)

**Comment by PanierAvide** [comment]
Seems good to me (tested under Chromium 46). If you are still having any issues with Monday/Sunday, please reopen this issue.

**Comment by d1g** [comment]
@PanierAvide, no issues with mo/su.

* Google Chrome 48.0.2564.0 canary
* Firefox 44.0a2
